packages:
  - ./docs/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': ^2.0.9
  '@acdh-oeaw/eslint-config-react': ^2.0.13
  '@acdh-oeaw/eslint-config-storybook': ^3.0.0
  '@acdh-oeaw/eslint-config-tailwindcss': ^3.0.0
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@acdh-oeaw/style-variants': ^0.1.0
  '@acdh-oeaw/stylelint-config': ^2.2.0
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@chromatic-com/storybook': ^4.0.1
  '@fontsource-variable/inter': ^5.2.6
  '@fontsource-variable/ubuntu-sans': ^5.2.8
  '@storybook/addon-a11y': ^9.0.16
  '@storybook/addon-docs': ^9.0.16
  '@storybook/addon-onboarding': ^9.0.16
  '@storybook/addon-themes': ^9.0.16
  '@storybook/addon-vitest': ^9.0.16
  '@storybook/react-vite': ^9.0.16
  '@tailwindcss/vite': ^4.1.11
  '@types/node': ^22.16.2
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react-swc': ^3.10.2
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  clsx: ^2.1.1
  eslint: ^9.30.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-turbo: ^2.5.4
  globals: ^16.3.0
  lucide-react: ^0.525.0
  npm-run-all2: ^8.0.4
  playwright: ^1.53.2
  prettier: ^3.6.2
  react: ^19.1.0
  react-aria-components: ^1.10.1
  react-dom: ^19.1.0
  storybook: ^9.0.16
  stylelint: ^16.21.1
  tailwindcss: ^4.1.11
  tailwindcss-react-aria-components: ^2.0.0
  tsdown: ^0.12.9
  typescript: ^5.8.3
  typescript-eslint: ^8.36.0
  vite: ^7.0.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  '@faker-js/faker': ^9.9.0
  tw-animate-css: ^1.3.5
  '@fontsource-variable/fira-code': ^5.2.6
  '@react-aria/utils': ^3.29.1

ignoredBuiltDependencies:
  - msw
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks
