import createPlugin from "tailwindcss/plugin";

export default createPlugin(({ addBase }) => {
	addBase({
		":root": {
			"--font-family-body": "var(--font-body, ui-sans-serif), system-ui, sans-serif",
			"--font-family-heading": "var(--font-body, ui-sans-serif), system-ui, sans-serif",

			"--color-neutral-0": "var(--color-white)",
			"--color-neutral-50": "var(--color-zinc-50)",
			"--color-neutral-100": "var(--color-zinc-100)",
			"--color-neutral-200": "var(--color-zinc-200)",
			"--color-neutral-300": "var(--color-zinc-300)",
			"--color-neutral-400": "var(--color-zinc-400)",
			"--color-neutral-500": "var(--color-zinc-500)",
			"--color-neutral-600": "var(--color-zinc-600)",
			"--color-neutral-700": "var(--color-zinc-700)",
			"--color-neutral-800": "var(--color-zinc-800)",
			"--color-neutral-900": "var(--color-zinc-900)",
			"--color-neutral-950": "var(--color-zinc-950)",
			"--color-neutral-1000": "var(--color-black)",

			"--color-negative-50": "var(--color-red-50)",
			"--color-negative-100": "var(--color-red-100)",
			"--color-negative-200": "var(--color-red-200)",
			"--color-negative-300": "var(--color-red-300)",
			"--color-negative-400": "var(--color-red-400)",
			"--color-negative-500": "var(--color-red-500)",
			"--color-negative-600": "var(--color-red-600)",
			"--color-negative-700": "var(--color-red-700)",
			"--color-negative-800": "var(--color-red-800)",
			"--color-negative-900": "var(--color-red-900)",
			"--color-negative-950": "var(--color-red-950)",

			"--color-positive-50": "var(--color-green-50)",
			"--color-positive-100": "var(--color-green-100)",
			"--color-positive-200": "var(--color-green-200)",
			"--color-positive-300": "var(--color-green-300)",
			"--color-positive-400": "var(--color-green-400)",
			"--color-positive-500": "var(--color-green-500)",
			"--color-positive-600": "var(--color-green-600)",
			"--color-positive-700": "var(--color-green-700)",
			"--color-positive-800": "var(--color-green-800)",
			"--color-positive-900": "var(--color-green-900)",
			"--color-positive-950": "var(--color-green-950)",

			"--color-notice-50": "var(--color-amber-50)",
			"--color-notice-100": "var(--color-amber-100)",
			"--color-notice-200": "var(--color-amber-200)",
			"--color-notice-300": "var(--color-amber-300)",
			"--color-notice-400": "var(--color-amber-400)",
			"--color-notice-500": "var(--color-amber-500)",
			"--color-notice-600": "var(--color-amber-600)",
			"--color-notice-700": "var(--color-amber-700)",
			"--color-notice-800": "var(--color-amber-800)",
			"--color-notice-900": "var(--color-amber-900)",
			"--color-notice-950": "var(--color-amber-950)",

			"--color-informative-50": "var(--color-sky-50)",
			"--color-informative-100": "var(--color-sky-100)",
			"--color-informative-200": "var(--color-sky-200)",
			"--color-informative-300": "var(--color-sky-300)",
			"--color-informative-400": "var(--color-sky-400)",
			"--color-informative-500": "var(--color-sky-500)",
			"--color-informative-600": "var(--color-sky-600)",
			"--color-informative-700": "var(--color-sky-700)",
			"--color-informative-800": "var(--color-sky-800)",
			"--color-informative-900": "var(--color-sky-900)",
			"--color-informative-950": "var(--color-sky-950)",
		},
	});
});
